"""
This module contains everything needed for reading an event log from a CSV file and produce a Generator that yields
events one by one in order to simulate an event stream.

DEFAULT_APROMORE_CSV_MAPPING includes a default mapping for CSV event logs generated by the
`apromore <https://academic-eu.apromore.org/>`_ simulation engine.
"""

from .mapping import DEFAULT_APROMORE_CSV_MAPPING, DEFAULT_CSV_MAPPING
from .reader import read_csv_log

__all__ = ["DEFAULT_APROMORE_CSV_MAPPING", "DEFAULT_CSV_MAPPING", "read_csv_log"]
